spring:
  application:
    name: order-admin
  config:
    name: order-admin
  jmx:
    default-domain: order-admin

server:
  port: ${randomServerPort.value[1000,5000]}
  servlet:
    application-display-name: order-admin
    context-path: /

ribbon:
  eager-load:
      enabled: true
      clients: admin-console-webapp
logging:
  config: classpath:logback.xml
